# Generated by Django 3.1.1 on 2020-10-11 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_addtocart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addtocart',
            old_name='Total',
            new_name='TotalPrice',
        ),
    ]
