# Generated by Django 3.1.1 on 2020-10-11 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_auto_20201011_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addtocart',
            old_name='TotalPrice',
            new_name='totalprice',
        ),
    ]
