# Generated by Django 3.1.1 on 2020-10-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_remove_order_product_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_product',
            old_name='state',
            new_name='state_city',
        ),
    ]
