# Generated by Django 3.1.1 on 2020-10-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_auto_20201014_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_product',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
