# Generated by Django 3.1.1 on 2020-10-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_order_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_product',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order_product',
            name='order_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order_product',
            name='payment_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order_product',
            name='payment_status',
            field=models.CharField(default='Not Done', max_length=100),
        ),
        migrations.AlterField(
            model_name='order_product',
            name='status',
            field=models.CharField(choices=[['Order Confirmed', 'Order Confirmed'], ['Shipped', 'Shipped'], ['Out for Delivery', 'Out for Delivery'], ['Delivered', 'Delivered']], max_length=100, null=True),
        ),
    ]
