# Generated by Django 3.1.1 on 2020-10-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0014_auto_20201015_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_product_detail',
            name='estimated_date',
            field=models.DateField(null=True),
        ),
    ]
