# Generated by Django 3.0 on 2020-06-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('service_name', models.CharField(max_length=200)),
                ('service_discription', models.CharField(max_length=300)),
                ('contact_email', models.CharField(max_length=200)),
                ('service_provider_id', models.CharField(max_length=200)),
            ],
        ),
    ]
