# Generated by Django 3.1.1 on 2020-10-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindapp', '0002_remove_manageruser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageruser',
            name='company',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
